### ISSUE TITLE
Code readability

### ISSUE THREAD

**Issue by thaven** [trishume/ddbus#29]
Code formatting in this project has been bothering me since I started working on it. General D coding guidelines are not applied at all. Unusual, but acceptable is the indent by two (rather than four) spaces. More of a problem is the placement of braces at the start of classes/structs/functions. Placing those braces at their own lines will vastly improve readability, especially when dealing with template constraints (which now too easily appear like an `if` statement if placed on their own line).

My proposal is to reformat the code base according to these rules:
* Generally follow the D style guidelines (https://dlang.org/dstyle.html)
  The 'additional requirements for Phobos', also documented on that page, do not apply.
* As an exception to that, we keep the two space indent.
  This respects the history of this project, by avoiding a reformatting commit changing nearly all lines of the code.
* Add a space between a keyword and a subsequent `(`, but not between a function name and a `(`.
* Block statement opening braces are at the end of the line containing the statement they belong to, closing braces are at the beginning of a line. If the same statement continues after that, it goes on at the same line as the closing brace.
  E.g.:
  ```D
  if (cond) {
    ...
  } else {
    ...
  }
  ```
  or
  ```D
  try {
    doSomethingHere();
  } catch (Exception evil) {
    saveTheWorldFrom(evil);
  }
  ```
  
* Private member variables of a struct or class are prefixed with `_`.

**Comment by trishume** [comment]
I'm okay with this. If @WebFreak001 is also okay with this, go ahead.

**Comment by WebFreak001** [comment]
I agree, it was bothering me when I was working with it too. But in order to keep this consistent we should be using dfmt. Something which comes close to your suggestions with dfmt would be this editorconfig:

```ini
[*]
dfmt_brace_style = otbs
dfmt_space_after_keywords = true
dfmt_space_after_cast = true
indent_style = space
indent_size = 2
```

**Comment by thaven** [comment]
I agree auto-formatting would generally be the right thing to do. However, `dfmt` actually doesn't really do its full job yet. (For example, when applying `otbs` style, it won't add braces to single-line conditionals.)

Also, it does not seem to support a style that places braces the way I'd like them. When limiting our choices to what `dfmt` supports, it's tempting to go with 'allman', as it's the only one that places the opening brace of a function on its own line (which I'd really like).

Also, `dfmt` doesn't respect a choice to list function parameters vertically when they won't fit on one line. E.g. (from `ddbus.exception`)
```D
package T wrapErrors(T)(
  T delegate(DBusError *err) del,
  string file = __FILE__,
  size_t line = __LINE__,
  Throwable next = null
) {
  // ...
}
```
gets reformatted by dfmt (`otbs` style) like
```D
package T wrapErrors(T)(T delegate(DBusError* err) del, string file = __FILE__,
    size_t line = __LINE__, Throwable next = null) {
  // ...
}
```

The first one is definitely more readable.

So yes, `dfmt` will certainly help maintaining a consistent formatting, but it won't bring us optimal readability.
