### ISSUE TITLE
Add support for dictionary types

### ISSUE THREAD

**Issue by dsboger-zz** [trishume/ddbus#3]
I'm investigating the possibility of using `ddbus` to write a GNOME Shell search provider [1] for Terminix [2], but the interface for the search provider defines a method GetResultMetas whose return type signature is aa{sv}. I've scanned `ddbus` source code but could not find support for this data type. Are there any plans to support dictionary types?

[1] https://developer.gnome.org/SearchProvider/
[2] https://github.com/gnunn1/terminix

**Comment by trishume** [comment]
I made an attempt at adding support for serializing and deserializing associative arrays as dictionaries in [this branch](https://github.com/trishume/ddbus/compare/dicts).

However the dbus service on my computer (OSX) is no longer working, so I can't actually test that my code works. All I can tell you is that it compiles on my version of D, if it doesn't compile for you try reverting the most recent commit on the branch which fixes a change in methods between versions.

If you test the code and tell me it works, or contribute any fixes necessary to get it to work, I'll merge it into master.

**Comment by WebFreak001** [comment]
bump for PR
