### ISSUE TITLE
Add support for meson

### ISSUE THREAD

**Issue by Cogitri** [trishume/ddbus#44]
It'd be nice if a shared lib of ddbus could be built via meson. I'll look into implementing this soon-ish.

**Comment by WebFreak001** [comment]
the project is very simple, just compiling all source files together as a library. What would be benefits in supporting another build system here? I could imagine this is something that would easily be automatically generatable

There is actually one dependency which is only used when unittesting though, which might be worth separating into only being compiled when in unittest configuration

**Comment by Cogitri** [comment]
> The project is very simple, just compiling all source files together as a library. What would be benefits in supporting another build system here?

Then it'll be simple to support meson too. Meson will make installation for distributions way nicer since with Meson it's very easy to generate a pkg-config file, a shared library and to install the D files for importing, all to the right locations.

**Comment by Cogitri** [comment]
E.g. all dependencies of dcd support meson, so it was very easy for me to add dcd to the Alpine Linux repositories, fully dynamically linked instead of getting a static build via dub.

**Comment by Cogitri** [comment]
> There is actually one dependency which is only used when unittesting though, which might be worth separating into only being compiled when in unittest configuration

Meson can detect dub packages, so if its only for testing that wouldn't be a problem to integrate.

**Comment by FFY00** [comment]
Yes, the benefits here are that we can install it on the system, and very easily also have a pkgconfig file installed.
