### ISSUE TITLE
How to list all the removable devices with DBus and UDisks2?

### ISSUE THREAD

**Issue by adnan449** [trishume/ddbus#46]
I need to list, filter and open block devices with UDisks2. I am trying to list all the removable devices. 

The [`GetBlockDevices` method](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Manager.html#gdbus-method-org-freedesktop-UDisks2-Manager.GetBlockDevices) provided by UDisks2 requires a `a{sv}` type. If I am not mistaken, it's a HashTable of string keys and Variant values.

How can I use this information to list the devices? So far I tried the following:

```d
import std.stdio, ddbus;
import ddbus: Variant;

void main()
{
	Connection conn = connectToBus();
	PathIface obj = new PathIface(conn, "org.freedesktop.DBus",
			"/org/freedesktop/UDisks2/Manager", "org.freedesktop.UDisks2.Manager");

	Variant!string[string] arg;
	writeln(obj.call!string("GetBlockDevices", arg));
}
```

The [`call`](https://ddbus.dpldocs.info/source/ddbus.simple.d.html#L22) method requires an `Arg` at as it's last parameter. 
For args, I used `Variant!string[string]` since Variant itself is a templated type.

However I am getting the following error:
> ddbus.exception.DBusException@../../.dub/packages/ddbus-2.3.0/ddbus/source/ddbus/thin.d(833): org.freedesktop.DBus does not understand message GetBlockDevices

**Comment by WebFreak001** [comment]
you are passing the wrong bus name, you need to pass `org.freedesktop.UDisks2` as bus name, see http://storaged.org/doc/udisks2-api/latest/ref-dbus-overview.html#ref-dbus-well-known-name

Also `Variant!string` means the type is serialized as variant but it may only contain a string. If you want to support other values than strings, you will want to use `Variant!DBusAny` (lightweight and full protocol data introspection) or `std.variant : Variant` (wider compatibility) instead.

Also tip: you can use `busName("..."), ObjectPath("/..."), interfaceName("...")` for calling the API in a type-safe and more readable way, see https://github.com/WebFreak001/DWin-Bar/blob/master/source/dwinbar/widgets/battery.d#L54

**Comment by adnan449** [comment]
@WebFreak001 I initially tried that particular bus name before. But it looks like udisks2 service is not running while it's not the case.

```d
import std.stdio, ddbus;
import ddbus: Variant, DBusAny;

void main()
{
	Connection conn = connectToBus();
	PathIface obj = new PathIface(conn, "org.freedesktop.UDisks2",
			"/org/freedesktop/UDisks2/Manager", "org.freedesktop.UDisks2.Manager");

	Variant!DBusAny[string] arg;
	writeln(obj.call!string("GetBlockDevices", arg));
}
```
```
$ ./dbed 
ddbus.exception.DBusException@../../.dub/packages/ddbus-2.3.0/ddbus/source/ddbus/thin.d(833): The name org.freedesktop.UDisks2 was not provided by any .service files
```

```
$ systemctl status udisks2
● udisks2.service - Disk Manager
     Loaded: loaded (/lib/systemd/system/udisks2.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-08-21 21:44:17 AEST; 3 days ago
       Docs: man:udisks(8)
   Main PID: 1075 (udisksd)
      Tasks: 5 (limit: 19046)
     Memory: 8.6M
     CGroup: /system.slice/udisks2.service
             └─1075 /usr/lib/udisks2/udisksd
```

**Comment by WebFreak001** [comment]
have you verified that the service does indeed exist in DBus yet? I recommend trying some application like D-Feet to try first.

**Comment by adnan449** [comment]
@WebFreak001 It is, as far as I understand. 

![image](https://i.imgur.com/bdioFiP.png)

**Comment by WebFreak001** [comment]
you are in the system bus there, I think in your code you are trying to use the session bus.

So you need to do:

```d
Connection conn = connectToBus(DBusBusType.DBUS_BUS_SYSTEM);
```

**Comment by adnan449** [comment]
https://stackoverflow.com/questions/63537158/how-to-list-all-the-removable-devices-with-dbus-and-udisks2/63580867#63580867
