### ISSUE TITLE
New release since the current one is broken

### ISSUE THREAD

**Issue by HenkKalkwater** [trishume/ddbus#48]
A while back, std.digest.digest got renamed to std.digest, which was fixed in #41. Since approximately libphobos version 1:2.094.2 (could be earlier or later, I'm running Arch which likely has a cutting-edge version), the deprecation warning has been turned into an error. It would be nice if a new release could be created with #41 included, so that adding this project as a dependency through dub would not cause the compilation to fail.

**Comment by WebFreak001** [comment]
there is v3.0.0-beta.1 which you can use already, there is probably not much more reason to keep it beta, but a few new things were added so some compatibility with old features might still be missing

**Comment by HenkKalkwater** [comment]
Seems like I didn't noticed that. Anyway, thank you for the library!
