### ISSUE TITLE
canDBus returns false for structs

### ISSUE THREAD

**Issue by quickfur** [trishume/ddbus#49]
Certain POD structs containing only fields of DBus-able types ought to be accepted by canDBus. Example of failing struct:

````
struct S {
    ObjectPath path;
    ubyte[] params;
    ubyte[] value;
    string type;
}
````

As a result of this limitation, `registerMethods` is unable to recognize a method that takes `S` as parameter, even though such a struct can be encoded in DBus as `(oayays)`.

**Comment by quickfur** [comment]
Huh, apparently it's because `canDBus!(ubyte[])` is false for some reason.

**Comment by quickfur** [comment]
ohhh, it's because `byte` is among `BasicTypes` but `ubyte` isn't, for whatever reason!

**Comment by WebFreak001** [comment]
oh you are right, `y` is unsigned, so `ubyte` should be supported instead of `byte`

As 3.0.0 isn't released as stable yet this is a good version to make byte unsupported and instead use ubyte

**Comment by quickfur** [comment]
so `byte` should be removed from `BasicTypes` then?

**Comment by WebFreak001** [comment]
`byte` should be replaced with `ubyte` in all dbus usage occurences (including BasicTypes)

**Comment by quickfur** [comment]
Submitted PR. :)

**Comment by quickfur** [comment]
Fixed, thanks for the quick merge!!
